import Head from "next/head";

import { Inter } from "@next/font/google";
import EditPage from "../components/pages/edit/EditPage";
import { useAppStore } from "../store";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Index() {
  const app = useAppStore();
  return (
    <>
      <Head>
        <title>{app.page.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <EditPage />
      </main>
    </>
  );
}
